### PR TITLE
Fix casing of GitHub

### PR DESCRIPTION
**Pull request by karlhorky**
Hey @ryyppy , nice project!

Quick PR to fix the casing of GitHub

### CODE REVIEW

**Comment by Schmavery** [comment]
Does this only change the bs.js file? Might want to tweak it here too: https://github.com/reason-association/reasonml.org/blob/1011d1beebffe45c9377c32e161c65ef94f10129/components/Navigation.re#L49

**Comment by ryyppy** [comment]
The GitHub reference will be gone when #84 is merged :-P

**Comment by karlhorky** [comment]
Ok, I'll leave it open until #84 is merged, to increase visibility and to avoid others also submitting PRs :)

**Comment by ryyppy** [comment]
Fixed with #84

**Pull request closed without merging**
