### PR TITLE
Fix Inter font hinting issue

### PR DESCRIPTION
**Pull request by lesha1201**
Closes https://github.com/reason-association/reasonml.org/issues/211

I've used [fonttools](https://github.com/fonttools/fonttools) for subsetting [Inter font](https://github.com/rsms/inter)

Example of a command for subsetting a font
```bash
pyftsubset /Inter-3.13/Inter\ Web/Inter-Regular.woff2 --unicodes="U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" --verbose --flavor=woff2
```

Example of result on Windows 10 (2560x1440)

_Before:_
image

_After:_
image

### CODE REVIEW

**Comment by ryyppy** [comment]
This is looking good! Thanks for tackling this issue. 👍

Could you maybe add the command you used for generating the file as a comment within the font documentation as well? For the case we will need to regenerate the files later at some point?

I am not too well versed with font engines and I am not entirely sure what those unicodes represent. Are these just latin1 characters?

Another qestion: Is `display: switch` also essential for fixing the bug, or is this unrelated?

**Comment by lesha1201** [comment]
I'll make changes.

I took unicodes from google fonts for latin characters. I will add a comment for that. 

`font-display` isn't related to the issue but I noticed that Roboto has `swap` and also all google fonts comes with swap by default. Should I remove `font-display` for Inter?

**Comment by lesha1201** [comment]
@ryyppy Added comments

**Comment by ryyppy** [comment]
Looking good 🚀 

Great job!

**Pull request merged**
