### PR TITLE
favicon

### PR DESCRIPTION
**Pull request by vasco3**
This will display the favicon in the browser tab.

### CODE REVIEW

**Comment by vasco3** [comment]
just realized that this project is using an older version of next which still uses static folder instead of public for assets.. So this approach won't work for the favicon. I would have to add a _document.js in pages. Would that be OK ? Or should we wait until we upgrade next?

**Comment by ryyppy** [comment]
we'll only need to rename the static folder to public (didn't think about it yet).. will do that as soon as I got the blog infra PR in, since it touches a few related files. I can ping you as soon as it is ready?

**Comment by vasco3** [comment]
yeah no problem.
we will also need to update all the image paths in the jsx tags from `/static/image.png` to `/image.png`

**Comment by ryyppy** [comment]
i added the favicon after I refactored to the `/public/static` folder within PR #135... thanks for opening this PR though!

**Pull request closed without merging**
