### PR TITLE
More design changes

### LINKED ISSUE #88: Firefox: cannot scroll down to the bottom of the sidebar
I noticed that to get to the bottom of the sidebar on Firefox I have to scroll down to the bottom of the main page. You can see how the bottom of the sidebar is cropped in this screenshot from the 13" screen of my old macbook air. Works as intended on Chrome. Maybe something to keep in mind during #84 :)
Capture d’écran 2019-11-21 à 00 08 37

### PR DESCRIPTION
**Pull request by ryyppy**
- More design system alignment with the designer
- Restructuring of the API page (more distinct to the rest of the API)
- Navigation alignment

Fixes #88, #66, #81, #80

### CODE REVIEW

**Comment by MoOx** [comment]
Is there a way we could preview the modification (like Netlify & others services can do with preview build on generated domain)?

**Comment by ryyppy** [comment]
@MoOx there is! Do you see the `View deployment` button inside this PR?

image

**Comment by MoOx** [comment]
Oh I missed that! Thanks 👍

**Comment by MoOx** [comment]
I would go for a centered column, on my 15" laptop I have a column on the left & this feels a bit weird.

Do you want help to enhance the design somehow? I could go for small PRs with very tiny changes if you are open to :)

**Comment by ryyppy** [comment]
@MoOx This is still a draft PR, I'll be happy to receive feedback / PRs when the actual design is implemented!

**Pull request merged**
